export const filterOptions = [
  { id: 'playable', label: 'Playable' },
  { id: 'planned', label: 'Planned' },
  { id: 'solo', label: 'Solo' },
  { id: 'vs-ai', label: 'vs AI' },
  { id: 'local-2p', label: 'Local 2P' },
  { id: 'abstract', label: 'Abstract' },
  { id: 'grid', label: 'Grid' },
  { id: 'puzzle', label: 'Puzzle' },
  { id: 'card', label: 'Card' },
  { id: 'word', label: 'Word' },
  { id: 'quick', label: 'Quick' },
  { id: 'deep', label: 'Deep' },
]

export const modeLabels = {
  solo: 'Solo',
  'vs-ai': 'vs AI',
  'local-2p': 'Local 2P',
}

export const statusLabels = {
  playable: 'Playable',
  planned: 'Planned',
  idea: 'Idea',
}

export const statusOrder = { playable: 0, planned: 1, idea: 2 }

export function gameMatchesFilter(game, filter) {
  if (filter === 'playable') return game.status === 'playable'
  if (filter === 'planned') return game.status !== 'playable'
  return game.modes.includes(filter) || game.tags.includes(filter)
}

export const games = [
  {
    id: 'gomoku',
    title: 'Gomoku',
    category: 'Abstract Strategy',
    status: 'playable',
    modes: ['vs-ai', 'local-2p'],
    tags: ['abstract', 'grid', 'turn-based', 'deep'],
    complexity: 'Medium',
    duration: '5-20 min',
    visual: 'gomoku',
  },
  {
    id: 'morris',
    title: "Nine Men's Morris",
    category: 'Abstract Strategy',
    status: 'playable',
    modes: ['vs-ai', 'local-2p'],
    tags: ['abstract', 'turn-based', 'deep'],
    complexity: 'Medium',
    duration: '10-25 min',
    visual: 'morris',
  },
  {
    id: 'othello',
    title: 'Othello',
    category: 'Abstract Strategy',
    status: 'playable',
    modes: ['vs-ai', 'local-2p'],
    tags: ['abstract', 'grid', 'turn-based', 'quick'],
    complexity: 'Medium',
    duration: '10-20 min',
    visual: 'othello',
  },
  {
    id: 'connect4',
    title: '4 in a Row',
    category: 'Abstract Strategy',
    status: 'playable',
    modes: ['vs-ai', 'local-2p'],
    tags: ['abstract', 'grid', 'turn-based', 'quick'],
    complexity: 'Light',
    duration: '3-10 min',
    visual: 'connect4',
  },
  {
    id: 'checkers',
    title: 'Checkers',
    category: 'Abstract Strategy',
    status: 'playable',
    modes: ['vs-ai', 'local-2p'],
    tags: ['abstract', 'grid', 'turn-based'],
    complexity: 'Medium',
    duration: '10-25 min',
    visual: 'checkers',
  },
  {
    id: 'dots-boxes',
    title: 'Dots and Boxes',
    category: 'Grid Games',
    status: 'playable',
    modes: ['vs-ai', 'local-2p'],
    tags: ['grid', 'turn-based', 'quick'],
    complexity: 'Light',
    duration: '5-15 min',
    visual: 'dots',
  },
  {
    id: 'tic-tac-toe',
    title: 'Tic Tac Toe',
    category: 'Grid Games',
    status: 'planned',
    modes: ['vs-ai', 'local-2p'],
    tags: ['grid', 'turn-based', 'quick'],
    complexity: 'Light',
    duration: '1-3 min',
    visual: 'tictactoe',
  },
  {
    id: 'ultimate-tic-tac-toe',
    title: 'Ultimate Tic-Tac-Toe',
    category: 'Grid Games',
    status: 'planned',
    modes: ['vs-ai', 'local-2p'],
    tags: ['grid', 'turn-based', 'deep'],
    complexity: 'Medium',
    duration: '10-20 min',
    visual: 'ultimate',
  },
  {
    id: 'tic-tac-toe-disappear',
    title: 'Vanishing Tic Tac Toe',
    aliases: ['Tic Tac Toe Disappear', 'XOGone'],
    category: 'Grid Games',
    status: 'planned',
    modes: ['vs-ai', 'local-2p'],
    tags: ['grid', 'turn-based', 'quick'],
    complexity: 'Light',
    duration: '3-10 min',
    visual: 'vanish',
  },
  {
    id: 'ataxx',
    title: 'Ataxx',
    category: 'Abstract Strategy',
    status: 'playable',
    modes: ['vs-ai', 'local-2p'],
    tags: ['abstract', 'grid', 'turn-based'],
    complexity: 'Medium',
    duration: '5-15 min',
    visual: 'ataxx',
  },
  {
    id: 'nonogram',
    title: 'Nonogram',
    category: 'Puzzle',
    status: 'planned',
    modes: ['solo'],
    tags: ['puzzle', 'grid', 'solo'],
    complexity: 'Medium',
    duration: '5-30 min',
    visual: 'nonogram',
  },
  {
    id: 'backgammon',
    title: 'Backgammon',
    category: 'Race / Table',
    status: 'playable',
    modes: ['vs-ai', 'local-2p'],
    tags: ['turn-based', 'deep'],
    complexity: 'Medium',
    duration: '10-30 min',
    visual: 'backgammon',
  },
  {
    id: 'threes',
    title: 'Threes',
    category: 'Puzzle',
    status: 'planned',
    modes: ['solo'],
    tags: ['puzzle', 'grid', 'solo', 'quick'],
    complexity: 'Light',
    duration: '3-15 min',
    visual: 'threes',
  },
  {
    id: '2048',
    title: '2048',
    category: 'Puzzle',
    status: 'planned',
    modes: ['solo'],
    tags: ['puzzle', 'grid', 'solo', 'quick'],
    complexity: 'Light',
    duration: '3-15 min',
    visual: '2048',
  },
  {
    id: 'crosswords',
    title: 'Crosswords',
    category: 'Word Games',
    status: 'planned',
    modes: ['solo'],
    tags: ['word', 'puzzle', 'solo'],
    complexity: 'Medium',
    duration: '10-45 min',
    visual: 'crossword',
  },
  {
    id: 'chess',
    title: 'Chess',
    category: 'Abstract Strategy',
    status: 'planned',
    modes: ['vs-ai', 'local-2p'],
    tags: ['abstract', 'grid', 'turn-based', 'deep'],
    complexity: 'Deep',
    duration: '10-60 min',
    visual: 'chess',
  },
  {
    id: 'battleship',
    title: 'Battleship',
    category: 'Hidden Information',
    status: 'planned',
    modes: ['vs-ai', 'local-2p'],
    tags: ['grid', 'turn-based'],
    complexity: 'Light',
    duration: '10-20 min',
    visual: 'battleship',
  },
  {
    id: 'international-checkers',
    title: 'International Checkers',
    category: 'Abstract Strategy',
    status: 'planned',
    modes: ['vs-ai', 'local-2p'],
    tags: ['abstract', 'grid', 'turn-based', 'deep'],
    complexity: 'Deep',
    duration: '15-40 min',
    visual: 'draughts',
  },
  {
    id: 'hex',
    title: 'Hex',
    category: 'Abstract Strategy',
    status: 'planned',
    modes: ['vs-ai', 'local-2p'],
    tags: ['abstract', 'turn-based', 'deep'],
    complexity: 'Medium',
    duration: '10-30 min',
    visual: 'hex',
  },
  {
    id: 'mancala',
    title: 'Mancala',
    category: 'Abstract Strategy',
    status: 'planned',
    modes: ['vs-ai', 'local-2p'],
    tags: ['abstract', 'turn-based', 'quick'],
    complexity: 'Medium',
    duration: '5-15 min',
    visual: 'mancala',
  },
  {
    id: 'go',
    title: 'Go',
    category: 'Abstract Strategy',
    status: 'planned',
    modes: ['vs-ai', 'local-2p'],
    tags: ['abstract', 'grid', 'turn-based', 'deep'],
    complexity: 'Deep',
    duration: '20-90 min',
    visual: 'go',
  },
  {
    id: 'poker',
    title: 'Poker',
    category: 'Card Games',
    status: 'planned',
    modes: ['solo', 'local-2p'],
    tags: ['card'],
    complexity: 'Medium',
    duration: '10-45 min',
    visual: 'poker',
  },
  {
    id: 'uno',
    title: 'Uno',
    category: 'Card Games',
    status: 'planned',
    modes: ['vs-ai', 'local-2p'],
    tags: ['card', 'quick'],
    complexity: 'Light',
    duration: '5-20 min',
    visual: 'uno',
  },
  {
    id: 'solitaire',
    title: 'Solitaire',
    category: 'Card Games',
    status: 'planned',
    modes: ['solo'],
    tags: ['card', 'solo'],
    complexity: 'Light',
    duration: '5-20 min',
    visual: 'solitaire',
  },
  {
    id: 'pentago',
    title: 'Pentago',
    category: 'Abstract Strategy',
    status: 'idea',
    modes: ['vs-ai', 'local-2p'],
    tags: ['abstract', 'grid', 'turn-based', 'quick'],
    complexity: 'Medium',
    duration: '5-15 min',
    visual: 'pentago',
  },
  {
    id: 'quarto',
    title: 'Quarto',
    category: 'Abstract Strategy',
    status: 'idea',
    modes: ['vs-ai', 'local-2p'],
    tags: ['abstract', 'grid', 'turn-based', 'quick'],
    complexity: 'Medium',
    duration: '5-15 min',
    visual: 'quarto',
  },
  {
    id: 'quoridor',
    title: 'Quoridor',
    category: 'Abstract Strategy',
    status: 'idea',
    modes: ['vs-ai', 'local-2p'],
    tags: ['abstract', 'grid', 'turn-based'],
    complexity: 'Medium',
    duration: '10-25 min',
    visual: 'quoridor',
  },
  {
    id: 'mastermind',
    title: 'Mastermind',
    category: 'Puzzle',
    status: 'idea',
    modes: ['solo'],
    tags: ['puzzle', 'solo'],
    complexity: 'Light',
    duration: '5-15 min',
    visual: 'mastermind',
  },
  {
    id: 'sudoku',
    title: 'Sudoku',
    category: 'Puzzle',
    status: 'playable',
    modes: ['solo'],
    tags: ['puzzle', 'grid', 'solo'],
    complexity: 'Medium',
    duration: '5-45 min',
    visual: 'sudoku',
  },
  {
    id: 'minesweeper',
    title: 'Minesweeper',
    category: 'Puzzle',
    status: 'idea',
    modes: ['solo'],
    tags: ['puzzle', 'grid', 'solo', 'quick'],
    complexity: 'Light',
    duration: '2-10 min',
    visual: 'minesweeper',
  },
  {
    id: 'set',
    title: 'Set',
    category: 'Card Games',
    status: 'idea',
    modes: ['solo', 'local-2p'],
    tags: ['card', 'puzzle', 'quick'],
    complexity: 'Medium',
    duration: '5-20 min',
    visual: 'set',
  },
  {
    id: 'yahtzee',
    title: 'Yahtzee',
    category: 'Dice Games',
    status: 'idea',
    modes: ['solo', 'local-2p'],
    tags: ['turn-based', 'quick'],
    complexity: 'Light',
    duration: '10-20 min',
    visual: 'dice',
  },
  {
    id: 'cribbage',
    title: 'Cribbage',
    category: 'Card Games',
    status: 'idea',
    modes: ['vs-ai', 'local-2p'],
    tags: ['card', 'turn-based'],
    complexity: 'Medium',
    duration: '15-35 min',
    visual: 'cribbage',
  },
  {
    id: 'hive',
    title: 'Hive',
    category: 'Abstract Strategy',
    status: 'idea',
    modes: ['vs-ai', 'local-2p'],
    tags: ['abstract', 'turn-based', 'deep'],
    complexity: 'Deep',
    duration: '10-25 min',
    visual: 'hive',
  },
]

export const playableCatalogGames = games.filter(game => game.status === 'playable')
export const playableCatalogGameIds = playableCatalogGames.map(game => game.id)
export const gamesById = Object.fromEntries(games.map(game => [game.id, game]))
